/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f8f9fa",
        "inverse-primary": "#66d9cc",
        "secondary-fixed": "#d6e4f9",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#001f23",
        "on-error": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "secondary": "#525f71",
        "error": "#ba1a1a",
        "on-background": "#191c1d",
        "primary-container": "#26a69a",
        "tertiary": "#006973",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f0f1f2",
        "outline": "#6d7a77",
        "outline-variant": "#bcc9c6",
        "surface-tint": "#4dbace",
        "tertiary-container": "#00a4b4",
        "primary-fixed": "#84f5e8",
        "on-secondary-fixed-variant": "#3a4859",
        "surface-dim": "#d9dadb",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary": "#ffffff",
        "surface-container": "#edeeef",
        "primary-fixed-dim": "#66d9cc",
        "secondary-fixed-dim": "#bac8dc",
        "secondary-container": "#d3e1f6",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#005049",
        "on-primary-container": "#003430",
        "on-secondary-container": "#566475",
        "on-primary-fixed": "#00201d",
        "error-container": "#ffdad6",
        "surface-container-high": "#e7e8e9",
        "tertiary-fixed-dim": "#56d7e9",
        "on-secondary-fixed": "#001d31",
        "on-tertiary-fixed-variant": "#004f57",
        "inverse-surface": "#2e3132",
        "on-tertiary-container": "#003339",
        "primary": "#4dbace",
        "on-surface": "#191c1d",
        "on-surface-variant": "#3d4947",
        "surface-variant": "#e1e3e4",
        "background": "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#93f1ff"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif']
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      }
    },
  },
  plugins: [],
}